export let items = {
    "tools": {
        "rustyKnife": {
            "name": "Rusty Knife", 
            "description": "Not the best but it will do the job",
            "uses": 25,
        },
        "kitchenKnife": {
            "name": "Kitchen Knife", 
            "description": "",
            "uses": 50,
        },
        "hatchet": {
            "name": "Hatchet",
            "description": "",
            "uses": 100,
        },
        "machete": {
            "name": "Machete",
            "description": "",
            "uses": 200,
        },
        "sword": {
            "name": "Sword",
            "description": "",
            "uses": 500,
        },
        "axe": {
            "name": "Axe",
            "description": "",
            "uses": 1000,
        },
        "pickaxe": {
            "name": "Pickaxe",
            "description": "",
            "uses": 2000,
        },
        "shovel": {
            "name": "Shovel",
            "description": "",
            "uses": 5000,
        },
        "hammer": {
            "name": "Hammer",
            "description": "",
            "uses": 10000,
        },
        "sledgehammer": {
            "name": "Sledgehammer",
            "description": "",
            "uses": 20000,
        },
        "chainsaw": {
            "name": "Chainsaw",
            "description": "",
            "uses": 50000,
        },
        "rustySword": {
            "name": "Rusty Sword",
            "description": "",
            "uses": 100,
        },
        "rustyAxe": {
            "name": "Rusty Axe",
            "description": "",
            "uses": 200,
        },
        "rustyPickaxe": {
            "name": "Rusty Pickaxe",
            "description": "",
            "uses": 500,
        },
        "rustyShovel": {
            "name": "Rusty Shovel",
            "description": "",
            "uses": 1000,
        },
        "rustyHammer": {
            "name": "Rusty Hammer",
            "description": "",
            "uses": 2000,
        },
        "rustySledgehammer": {
            "name": "Rusty Sledgehammer",
            "description": "",
            "uses": 5000,
        },
        "rustyChainsaw": {
            "name": "Rusty Chainsaw",
            "description": "",
            "uses": 10000,
        },
        "rustyGun": {
            "name": "Rusty Gun",
            "description": "",
            "uses": 20000,
        },
        "rustyRifle": {
            "name": "Rusty Rifle",
            "description": "",
            "uses": 50000,
        },
        "rustyShotgun": {
            "name": "Rusty Shotgun",
            "description": "",
            "uses": 100000,
        },
        "rustySniper": {
            "name": "Rusty Sniper",
            "description": "",
            "uses": 200000,
        },
        "rustyRocketLauncher": {
            "name": "Rusty Rocket Launcher",
            "description": "",
            "uses": 500000,
        },
        "rustyGrenadeLauncher": {
            "name": "Rusty Grenade Launcher",
            "description": "",
            "uses": 1000000,
        },
        "rustyFlamethrower": {
            "name": "Rusty Flamethrower",
            "description": "",
            "uses": 2000000,
        },
        "rustyLaser": {
            "name": "Rusty Laser",
            "description": "",
            "uses": 5000000,
        },
        "rustyNuke": {
            "name": "Rusty Nuke",
            "description": "",
            "uses": 10000000,
        },
        "rustyNuclearBomb": {
            "name": "Rusty Nuclear Bomb",
            "description": "",
            "uses": 20000000,
        },
        "rustyNuclearMissile": {
            "name": "Rusty Nuclear Missile",
            "description": "",
            "uses": 50000000,
        },        
    },
    "weapons": {
        "gun": {
            "name": "Gun",
            "description": "",
            "uses": 20000,
        },
        "rifle": {
            "name": "Rifle",
            "description": "",
            "uses": 50000,
        },
        "shotgun": {
            "name": "Shotgun",
            "description": "",
            "uses": 100000,
        },
        "sniper": {
            "name": "Sniper",
            "description": "",
            "uses": 200000,
        },
        "rocketLauncher": {
            "name": "Rocket Launcher",
            "description": "",
            "uses": 500000,
        },
        "grenadeLauncher": {
            "name": "Grenade Launcher",
            "description": "",
            "uses": 1000000,
        },
        "flamethrower": {
            "name": "Flamethrower",
            "description": "",
            "uses": 2000000,
        },
        "laser": {
            "name": "Laser",
            "description": "",
            "uses": 5000000,
        },
        "nuke": {
            "name": "Nuke",
            "description": "",
            "uses": 10000000,
        },
        "nuclearBomb": {
            "name": "Nuclear Bomb",
            "description": "",
            "uses": 20000000
        },
    },
    "vehicles": {
        "car": {
            "name": "Car",
            "description": "",
            "uses": 20000,
        },
        "truck": {
            "name": "Truck",
            "description": "",
            "uses": 50000,
        },
        "tank": {
            "name": "Tank",
            "description": "",
            "uses": 100000,
        },
        "plane": {
            "name": "Plane",
            "description": "",
            "uses": 200000,
        },
        "helicopter": {
            "name": "Helicopter",
            "description": "",
            "uses": 1000,
        },
        "rocket": {
            "name": "Rocket",
            "description": "",
            "uses": 500000,
        },
        "spaceship": {
            "name": "Spaceship",
            "description": "",
            "uses": 1000000,
        },
        "submarine": {
            "name": "Submarine",
            "description": "",
            "uses": 2000000,
        },
        "airship": {
            "name": "Airship",
            "description": "",
            "uses": 5000000,
        },
    },
    "food": {
        "apple": {
            "name": "Apple",
            "description": "",
            "health": 0,
            "sleep": 0,
            "food": 3,
            "water": 0,
        },
        "banana": {
            "name": "Banana",
            "description": "",
            "health": 0,
            "sleep": 0,
            "food": 7,
            "water": 0,
        },
        "orange": {
            "name": "Orange",
            "description": "",
            "health": 0,
            "sleep": 0,
            "food": 5,
            "water": 0,
        },
        "watermelon": {
            "name": "Watermelon",
            "description": "",
            "health": 0,
            "sleep": 0,
            "food": 15,
            "water": 0,
        },
        "carrot": {
            "name": "Carrot",
            "description": "",
            "health": 0,
            "sleep": 0,
            "food": 10,
            "water": 0,
        },
        "potato": {
            "name": "Potato",
            "description": "",
            "health": 0,
            "sleep": 0,
            "food": 10,
            "water": 0,
        },
        "honey": {
            "name": "Honey", 
            "description": "Sweet and delicious",
            "health": 1,
            "sleep": 0,
            "food": 10,
            "water": -5,
        },
    },
    "drinks": {
        "waterBottle": {
            "name": "Water Bottle", 
            "description": "Just safe water",
            "health": 0,
            "sleep": 0,
            "food": 0,
            "water": 20,
        },
        "coffee": {
            "name": "Coffee", 
            "description": "Warm and invigorating",
            "health": 0,
            "sleep": 10,
            "food": 0,
            "water": 5,
        },
        "bread": {
            "name": "Bread", 
            "description": "A little crunchy",
            "health": 0,
            "sleep": 0,
            "food": 10,
            "water": -2,
        },
        "pasta": {
            "name": "Pasta", 
            "description": "Can be used to bake something delicious",
            "health": 0,
            "sleep": 0,
            "food": 0,
            "water": 0,
        },
    },
    "medicine": {
        "bandage": {
            "name": "Bandage",
            "description": "",
            "health": 10,
            "sleep": 0,
            "food": 0,
            "water": 0,
        },
        "painkiller": {
            "name": "Painkiller",
            "description": "",
            "health": 20,
            "sleep": 0,
            "food": 0,
            "water": 0,
        },
        "medicKit": {
            "name": "Medic Kit", 
            "description": "A complete healing kit",
            "health": 100,
            "sleep": 0,
            "food": 0,
            "water": 0,
        },
        "ointment": {
            "name": "Ointment", 
            "description": "It can help with injuries",
            "health": 10,
            "sleep": 0,
            "food": 0,
            "water": 0,
        },
    },
    "others": {
        "campFire": {
            "name": "Camp Fire", 
            "description": "One of the most useful things in survival",
            "health": 0,
            "sleep": 0,
            "food": 0,
            "water": 0,
            "duration": 1440, // 24 hours in minutes
        },
    },
};