export let items = {
    "honey": {
        "name": "Honey", 
        "description": "Sweet and delicious",
        "health": 1,
        "sleep": 0,
        "food": 10,
        "water": -5,
    },
    "waterBottle": {
        "name": "Water Bottle", 
        "description": "Just safe water",
        "health": 0,
        "sleep": 0,
        "food": 0,
        "water": 20,
    },
    "coffee": {
        "name": "Coffee", 
        "description": "Warm and invigorating",
        "health": 0,
        "sleep": 10,
        "food": 0,
        "water": 5,
    },
    "bread": {
        "name": "Bread", 
        "description": "A little crunchy",
        "health": 0,
        "sleep": 0,
        "food": 10,
        "water": -2,
    },
    "medicKit": {
        "name": "Medic Kit", 
        "description": "A complete healing kit",
        "health": 100,
        "sleep": 0,
        "food": 0,
        "water": 0,
    },
    "ointment": {
        "name": "Ointment", 
        "description": "It can help with injuries",
        "health": 10,
        "sleep": 0,
        "food": 0,
        "water": 0,
    },
};